import Footer from "./Components/Footer";
import Navbar from "./Components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "shop-client",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <Navbar/>
        <div className="container">
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
